package vn.com.cowmanager.model.arrangement;

import domainapp.basics.exceptions.ConstraintViolationException;
import domainapp.basics.model.meta.AttrRef;
import domainapp.basics.model.meta.DAttr;
import domainapp.basics.model.meta.DClass;
import domainapp.basics.model.meta.DOpt;
import domainapp.basics.model.meta.DAttr.Type;
import domainapp.basics.util.Tuple;

@DClass(schema = "arrangement")
public abstract class Person {
	@DAttr(name = "id", type = Type.String, id = true, auto = true, optional = false, mutable = false, length = 6)
	private String id;
	private static int idCounter = 0;

	@DAttr(name = "name", type = Type.String, optional = false, length = 25)
	private String name;

	@DAttr(name = "address", type = Type.String, length = 50)
	private String address;

	@DAttr(name = "phoneNum", type = Type.String, optional = false, length = 15)
	private String phoneNum;

	public Person(String id, String name, String address, String phoneNum) {
		this.id = nextId(id);
		this.name = name;
		this.address = address;
		this.phoneNum = phoneNum;
	}

	public Person(@AttrRef("name") String name, @AttrRef("address") String address,
			@AttrRef("phoneNumb") String phoneNum) {
		this(null, name, address, phoneNum);
	}

	public Person(@AttrRef("name") String name, @AttrRef("phoneNumb") String phoneNum) {
		this(null, name, null, phoneNum);
	}

	public String toString() {
		return "Person(" + id + "," + name + "," + phoneNum + ")";
	}

	// automatically generate the next student id
	protected String nextId(String id) throws ConstraintViolationException {
		if (id == null) { // generate a new id
			idCounter++;
			return "PE" + idCounter;
		} else {
			// update id
			int num;
			try {
				num = Integer.parseInt(id.substring(2));
			} catch (RuntimeException e) {
				throw new ConstraintViolationException(ConstraintViolationException.Code.INVALID_VALUE, e,
						new Object[] { id });
			}

			if (num > idCounter) {
				idCounter = num;
			}

			return id;
		}
	}

	/**
	 * @requires minVal != null /\ maxVal != null
	 * @effects update the auto-generated value of attribute <tt>attrib</tt>,
	 *          specified for <tt>derivingValue</tt>, using
	 *          <tt>minVal, maxVal</tt>
	 */
	@DOpt(type = DOpt.Type.AutoAttributeValueSynchroniser)
	public static void updateAutoGeneratedValue(DAttr attrib, Tuple derivingValue, Object minVal, Object maxVal)
			throws ConstraintViolationException {

		if (minVal != null && maxVal != null) {
			// TODO: update this for the correct attribute if there are more
			// than one auto attributes of this class

			String maxId = (String) maxVal;

			try {
				int maxIdNum = Integer.parseInt(maxId.substring(2));

				if (maxIdNum > idCounter) // extra check
					idCounter = maxIdNum;

			} catch (RuntimeException e) {
				throw new ConstraintViolationException(ConstraintViolationException.Code.INVALID_VALUE, e,
						new Object[] { maxId });
			}
		}
	}

	public String getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

}
